### ISSUE TITLE
Reset redeemed codes check in Google Script?

### ISSUE THREAD

**Issue by SubZeroNexii** [torikushiii/hoyolab-auto#101]
I used an incomplete cookie to run the script the first time and while daily logins worked all the code redeems gave me errors. I now changed the cookie with a complete one and it just skips trying to redeem codes altogether. Is there a way to reset this check?

I already removed the script properties from the script and even made a new project and I keep running into the same problem.

**Comment by torikushiii** [comment]
Hello, I’ve committed a new change to the Google Script code where you can now view and reset code redeems. It looks like this:

<img width="214" height="103" alt="Image" src="https://github.com/user-attachments/assets/8efb8094-0506-455c-8520-30e71bce322d" />

<img width="867" height="277" alt="Image" src="https://github.com/user-attachments/assets/d45b78b7-a413-42fb-8fbd-bb7bcae8e081" />


Is this what you meant with your issue?

**Comment by SubZeroNexii** [comment]
I used the resetAllRedemedCodes function and checked if they have been reset with viewAllRedeemedCodes but the script still does not try to get redeem new codes. Sorry if I wasn't specific enough with my issue.

My problem is the script stops trying to redeem codes if the daily logins have been completed.

I think the problem is that the code only returns a non-empty JSON if `data.isSigned` is false in the `checkAndExecute ()` function at line 177.

When it returns an empty array to the `checkInGame` function the for loop at line 576 is completely skipped

Here's a photo of the execution log:

<img width="572" height="374" alt="Image" src="https://github.com/user-attachments/assets/d335116e-6aa7-49db-859e-a5d796513783" />

**Comment by torikushiii** [comment]
Ah.. You want a bypass to redeem codes directly yes?

**Comment by SubZeroNexii** [comment]
Yes. I want a way to check if the cookies are working properly without waiting a day for a new daily log in

**Comment by torikushiii** [comment]
Latest commit should have this feature now where you can choose what game to redeem code for

<img width="204" height="102" alt="Image" src="https://github.com/user-attachments/assets/7008995d-75b4-4e8e-8c97-14cb824b4030" />
